language: elixir
elixir: '1.6.4'
otp_release: '20.1'
dist: xenial
addons:
  - postgresql: '9.6'
services:
  - postgresql
  - xvfb # Available in xenial
env:
  - MIX_ENV=test
cache:
  directories:
    - _build
    - deps

before_script:
  # From https://github.com/keathley/wallaby/blob/master/.travis.yml
  - export CHROMEDRIVER_VERSION=`curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE`
  - curl -L -O "http://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
  - unzip chromedriver_linux64.zip
  - sudo chmod +x chromedriver
  - sudo mv chromedriver /usr/local/bin
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo apt-get update
  - sudo apt-get --only-upgrade install google-chrome-stable
  - psql -c "create user magpie_dev with password 'magpie';" -U postgres
  - psql -c "alter user magpie_dev createdb" -U postgres
  - mix do ecto.create, ecto.migrate
  - mix test
  - mix coveralls.travis
