# Note that this Docker configuration is exclusively for starting up the server on a local machine so that experiments can be run by researchers even without any internet connection. The production web app is NOT deployed via Docker for now.
version: '3'
services:
  web:
    # The path that contains Dockerfile
    build: .
    # Map the 4000 of localhost to the 4000 of the container
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - DOCKER=true
    volumes:
      - babe-app-volume:/app
    # Ensures that the postgres service is started first.
    depends_on:
      - db
  db:
    image: postgres:10
    volumes:
      # Just preserve the postgresql data in the local folder.
      - babe-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: babe
      POSTGRES_USER: babe_dev
      POSTGRES_DB: babe_dev

volumes:
  babe-app-volume:
    external: true
  babe-db-volume:
    external: true
